### ISSUE TITLE
Logged in as another user

### ISSUE THREAD

**Issue by wvanlit** [alyssaxuu/carden#1]
When using my Google Account to log in to Carden, I instead got logged in as a user name "Olive You", who is already level 4 and has created cards.

![image](https://user-images.githubusercontent.com/44299782/122513757-20e49100-d00b-11eb-9011-b8b3f29d593c.png)

**Comment by alyssaxuu** [comment]
The current version in the Chrome store is just acting weird - basically it's not getting the user ID from the access token, apparently something to do with browser syncing. I've just updated it, 1.0.4 should be working fine.
